### ISSUE TITLE
CASAVA18 regexp failed validation

### ISSUE THREAD

**Issue by IsmailM** [enasequence/readtools#14]
I'm getting the following error:

```
, result: Line No. : 67511458 - uk.ac.ebi.ena.readtools.loader.common.producer.DataProducerException: Line [@D00623:83:C8DLYANXX:1:1101:1535:2140 3:N:0:CATTTT] does not match CASAVA18 regexp
ERROR: Line [@D00623:83:C8DLYANXX:1:1101:1535:2140 3:N:0:CATTTT] does not match CASAVA18 regexp [file: /home/ucbtmog/uploads/d/Diagenode_Ref-gDNA-100-2_R2.fastq.gz, line number: 67511458]
ERROR: Submission validation failed because of a user error. Please check validation reports for further information: /home/ucbtmog/uploads/./d/submissions/reads/EpiCapture/validate
```

I am seeing this in 16 different files.

* R1 always successfully passes validation
* And the issue in R2 is always in the middle of the file...

I see the following. What is the difference between CASAVA18 + fastq basenames? Looking at the regexes a the top of this file, the line in question passes the FASTQ regex...

https://github.com/enasequence/readtools/blob/e01046a4ef7aa1824700d12b150ae5a7ec5708d3/src/main/java/uk/ac/ebi/ena/readtools/loader/common/producer/DataSpotReader.java#L168-L202

**Comment by raskoleinonen** [comment]
The read name in this issue (@D00623:83:C8DLYANXX:1:1101:1535:2140 3:N:0:CATTTT) matches the current (latest) regexp (^@(.)( +\|\t)([0-9]+):[YN]:[0-9][02468]($\|:.$)). Fastq read name parsing code has been updated multiple times since this ticket was created. The problem may have been that the read pair number was 3, and when this ticket was created only 1 and 2 were allowed. 

I will close this ticket assuming that the problem has been resolved. Please re-open a new ticket if this is not the case.
